apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2VyCg==          # base64 encoded string for "mongouser"
  mongo-password: bW9uZ29wYXNzd29yZAo=  # base64 encoded string for "mongopassword"
  