apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:3.5.0
        command: ["bin/spark-class", "org.apache.spark.deploy.master.Master"]
        ports:
        - containerPort: 8080
        - containerPort: 7077
        volumeMounts:
        - mountPath: /opt/bitnami/jars
          name: volume-spark-master
      volumes:
      - name: volume-spark-master
        hostPath:
          path: /path/to/your/local/volume_spark_master

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  ports:
  - port: 7077
    targetPort: 7077
  selector:
    app: spark-master

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:3.5.0
        command: ["bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_WORKER_CORES
          value: "2"
        - name: SPARK_WORKER_MEMORY
          value: "1g"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"
        volumeMounts:
        - mountPath: /opt/bitnami/jars
          name: volume-spark-worker
      volumes:
      - name: volume-spark-worker
        hostPath:
          path: /path/to/your/local/volume_spark_worker